// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Infrastructure.Persistence;

#nullable disable

namespace Stock.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260428024230_AddInitialProcedures")]
    partial class AddInitialProcedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Domain.Entities.Box", b =>
                {
                    b.Property<int>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoxId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Box_CreatedAt");

                    b.Property<decimal>("Depth")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("ParentBoxId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Box_UpdatedAt");

                    b.Property<decimal>("Volume")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(15, 2)")
                        .HasComputedColumnSql("ISNULL(CAST(([Height] * [Width] * [Depth]) AS decimal(15, 2)), 0.0)", true);

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("BoxId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentBoxId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Box_Name");

                    b.ToTable("Box", t =>
                        {
                            t.HasCheckConstraint("CK_Box_Depth", "[Depth] > 0");

                            t.HasCheckConstraint("CK_Box_Height", "[Height] > 0");

                            t.HasCheckConstraint("CK_Box_Width", "[Width] > 0");
                        });
                });

            modelBuilder.Entity("Stock.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte>("IncludedIn")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("BrandId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Brand_Name");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte>("IncludedIn")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Category_Name");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Item_CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Item_UpdatedAt");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Item_Name");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LabelId");

                    b.HasIndex("Context", "LabelKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Label_Context_Key");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Language_IsDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageCode");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("UQ_Language_SingleDefault")
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorageId"));

                    b.Property<int>("BoxId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Storage_CreatedAt");

                    b.Property<bool>("Expires")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Storage_UpdatedAt");

                    b.HasKey("StorageId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ItemId");

                    b.HasIndex("BoxId", "ItemId", "BrandId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Storage_Box_Item_Brand");

                    b.ToTable("Storage", t =>
                        {
                            t.HasCheckConstraint("CK_Storage_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Stock.Domain.Entities.Translation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Translation_CreatedAt");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()", "DF_Translation_UpdatedAt");

                    b.HasKey("TranslationId");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LabelId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Translation_Label_Language");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Views.BoxDetailed", b =>
                {
                    b.Property<int>("BoxId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Depth")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("FullPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentBoxId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(5, 2)");

                    b.ToTable("BoxDetailed", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Stock.Domain.Entities.Box", b =>
                {
                    b.HasOne("Stock.Domain.Entities.Brand", "Brand")
                        .WithMany("Boxes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Box_BrandId");

                    b.HasOne("Stock.Domain.Entities.Category", "Category")
                        .WithMany("Boxes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Box_CategoryId");

                    b.HasOne("Stock.Domain.Entities.Box", "ParentBox")
                        .WithMany("SubBoxes")
                        .HasForeignKey("ParentBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Box_ParentBoxId");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("ParentBox");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Item", b =>
                {
                    b.HasOne("Stock.Domain.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Item_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Storage", b =>
                {
                    b.HasOne("Stock.Domain.Entities.Box", "Box")
                        .WithMany("Storages")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Storage_BoxId");

                    b.HasOne("Stock.Domain.Entities.Brand", "Brand")
                        .WithMany("Storages")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Storage_BrandId");

                    b.HasOne("Stock.Domain.Entities.Item", "Item")
                        .WithMany("Storages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Storage_ItemId");

                    b.Navigation("Box");

                    b.Navigation("Brand");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Translation", b =>
                {
                    b.HasOne("Stock.Domain.Entities.Label", "Label")
                        .WithMany("Translations")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Translation_LabelId");

                    b.HasOne("Stock.Domain.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Translation_LanguageCode");

                    b.Navigation("Label");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Box", b =>
                {
                    b.Navigation("Storages");

                    b.Navigation("SubBoxes");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Category", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Item", b =>
                {
                    b.Navigation("Storages");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Label", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Stock.Domain.Entities.Language", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
