name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ] 
    paths:
      - 'back/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'back/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Download Code
      uses: actions/checkout@v5

    - name: 2. Install .Net SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x 
        cache: true
        cache-dependency-path: back/Stock.slnx

    - name: 3. Restore Packages (NuGet)
      run: dotnet restore back/Stock.slnx

    - name: 4. Compile (Build)      
      run: dotnet build --no-restore --configuration Release --no-incremental
      working-directory: ./back

    - name: 5. Run Unit Tests      
      run: dotnet test --no-build --configuration Release --verbosity normal --logger "github;summary=true"
      working-directory: ./back